# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project.common


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=30, verbose_name='title')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(project.common.BaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=30, verbose_name='title')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(project.common.BaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ticker', models.CharField(max_length=10, verbose_name='ticker')),
                ('name', models.CharField(max_length=80, verbose_name='company name')),
                ('exchange', models.CharField(choices=[('xnys', 'xnys'), ('xnas', 'xnas')], max_length=10)),
                ('market_cap', models.BigIntegerField(default=0, verbose_name='market cap')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='tool.Industry')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='tool.Sector')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(project.common.BaseMixin, models.Model),
        ),
    ]
