# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='value',
            field=models.CharField(default='', max_length=30, verbose_name='value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='value',
            field=models.CharField(default='', max_length=30, verbose_name='value'),
            preserve_default=False,
        ),
    ]
