# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20160630_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
