# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20160630_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='beta',
            field=models.FloatField(blank=True, null=True, verbose_name='long term debt to equity'),
        ),
        migrations.AddField(
            model_name='stock',
            name='ipo_date',
            field=models.DateField(blank=True, null=True, verbose_name='ipo date'),
        ),
        migrations.AddField(
            model_name='stock',
            name='ltdebt_equity',
            field=models.FloatField(blank=True, null=True, verbose_name='long term debt to equity'),
        ),
    ]
