# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_auto_20160704_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='dcf_value',
            field=models.FloatField(blank=True, null=True, verbose_name='dcf value'),
        ),
        migrations.AddField(
            model_name='stock',
            name='net_debt',
            field=models.BigIntegerField(default=0, verbose_name='net debt'),
        ),
    ]
